aliyun:
    oss:
        bucketName: hmleadnewsxu
        endpoint: https://oss-us-west-1.aliyuncs.com
mybatis:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true
server:
    tomcat:
        threads:
            max: 500
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 20020421
        url: jdbc:mysql://localhost:3306/mybatis
        username: root
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 100MB

#spring事务管理日志
logging:
    level:
        org.springframework.jdbc.support.JdbcTransactionManager: debug
